name: CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
env:
  CSV_URL: "MLproject/prdectid_preprocessing.csv"
  BUILD_TAG: "sentiment-analysis:v1.0.${{ github.run_number }}"
 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Check Env
        run: |
          echo $CSV_URL
          echo $BUILD_TAG
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0
      
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local --experiment-name "Workflow CI"
 
      - name: Set up Git LFS
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main
          
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main

      - name: Build docker model
        run: |
          mlflow models build-docker -m models:/sentiment-analysis/latest -name $BUILD_TAG
          
      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PAT }}
      
      - name: Tag Docker Image
        run: |
          docker tag $BUILD_TAG reyndev/mlflow-sentiment-analysis:v1.0.${{ github.run_number }}
      
      - name: Push Docker Image
        run: |
          docker push reyndev/mlflow-sentiment-analysis:v1.0.${{ github.run_number }}
